server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  main:
    web-application-type: servlet
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR